---
# roles/R/tasks/main.yml

- name: "Install R version {{ r_target_version }} using appsilon.r_language role"
  become: true
  ansible.builtin.include_role:
    name: appsilon.r_language
  vars:
    r_versions: # This is the var expected by appsilon.r_language
      - "{{ r_target_version }}"
    # If appsilon.r_language allows configuring its install prefix to match
    # your r_install_base_path, you could pass that too.
    # For now, we assume it defaults to /opt/R or is not easily changed by its own vars.

- name: "Ensure symlink target directory {{ r_symlink_target_dir }} exists"
  become: true
  ansible.builtin.file:
    path: "{{ r_symlink_target_dir }}"
    state: directory
    mode: '0755'

- name: "Create symlinks for R {{ r_target_version }} executables in {{ r_symlink_target_dir }}"
  become: true
  ansible.builtin.file:
    src: "{{ r_install_base_path }}/{{ r_target_version }}/bin/{{ item }}"
    dest: "{{ r_symlink_target_dir }}/{{ item }}"
    state: link
    force: yes # Overwrite if symlink exists or is a different type of file
    mode: '0755' # Permissions for the symlink itself
  loop: "{{ r_executables_to_symlink }}"
  loop_control:
    label: "Symlinking {{ item }} for R {{ r_target_version }}"

