---
# roles/devpod/defaults/main.yml

# You can set a specific version or use "latest"
# To find specific versions, check: https://github.com/loft-sh/devpod/releases
devpod_version: "latest" # Or a specific version like "v0.6.15"

# Base URL for DevPod releases on GitHub
devpod_github_url: "https://github.com/loft-sh/devpod/releases"

# Determine architecture (amd64 or arm64)
devpod_arch_map:
  x86_64: amd64
  aarch64: arm64
  arm64: arm64 # Some systems report 'arm64' for aarch64

devpod_architecture: "{{ devpod_arch_map[ansible_architecture] | default('amd64') }}"

# Construct the download URL
devpod_download_url_latest: "{{ devpod_github_url }}/latest/download/devpod-linux-{{ devpod_architecture }}"
devpod_download_url_versioned: "{{ devpod_github_url }}/download/{{ devpod_version }}/devpod-linux-{{ devpod_architecture }}"
devpod_download_url: "{{ (devpod_version == 'latest') | ternary(devpod_download_url_latest, devpod_download_url_versioned) }}"

# Installation path for the DevPod CLI
devpod_install_path: "/usr/local/bin/devpod"

# Temporary download location
devpod_tmp_download_path: "/tmp/devpod-{{ devpod_architecture }}"

