# roles/miniconda/defaults/main.yml

# Specific Miniconda version/script name details
# Find latest at https://docs.conda.io/en/latest/miniconda.html
miniconda_installer_script_name: "Miniconda3-latest-Linux-x86_64.sh" # Or a specific versioned script
miniconda_installer_url_base: "https://repo.anaconda.com/miniconda/"
miniconda_installer_url: "{{ miniconda_installer_url_base }}{{ miniconda_installer_script_name }}"

# User-specific installation path
miniconda_install_path: "{{ ansible_env.HOME }}/miniconda3"

# Shells to initialize for conda
miniconda_init_shells:
  - bash
