# local.yml

---
- name: Provision local Tuxedo OS machine for development
  hosts: localhost

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all installed packages
      become: true
      ansible.builtin.apt:
        upgrade: dist

    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

  roles:
    # Add ssh key and config
    - role: ssh

    # Install common developer tools
    - role: apt

    # Add user.name and user.email to .gitconfig
    - role: git

    # Add JetBrainsMono Nerd Font
    - role: nerdfont

    # Add docker via ansible-galaxy geerlingguy.docker
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user_id }}" # Adds the current ansible user to the docker group
