# local.yml

---
- name: Provision local Tuxedo OS machine for development
  hosts: localhost

  pre_tasks:
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all installed packages
      become: true
      ansible.builtin.apt:
        upgrade: dist

    - name: Install apt packages
      become: true
      ansible.builtin.apt:
        pkg:
          - fzf
          - kitty
          - libcurl4-openssl-dev
          - libfontconfig1-dev
          - libfreetype6-dev
          - libfribidi-dev
          - libharfbuzz-dev
          - libjpeg-dev
          - libpng-dev
          - libssl-dev
          - libtiff5-dev
          - libxml2-dev
          - luarocks
          - stow
          - tmux
          - xclip

    - name: Add the flathub flatpak repository remote to the user installation
      become: true
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install flatpak packages
      become: true
      community.general.flatpak:
        name: md.obsidian.Obsidian
        state: present

  roles:
    # Add ssh key and config
    - role: ssh

    # Add user.name and user.email to .gitconfig
    - role: git

    # Add docker via ansible-galaxy geerlingguy.docker
    - role: geerlingguy.docker
      become: true
      vars:
        docker_users:
          - "{{ ansible_user_id }}" # Adds the current ansible user to the docker group

    # Add Neovim via gikeymarcia.neovim
    - role: gikeymarcia.neovim
      become: true

    # Add Starship Prompt via andrewrothstein.starship
    - role: andrewrothstein.starship

    - role: hurricanehrndz.nerdfonts
      become: true
      vars:
        nerdfonts_mono: yes
        nerdfonts_fonts:
          - fontname: 'FiraCode' # Specify the base font name. 'nerdfonts_mono: yes' handles the mono aspect.
        nerdfonts_users: [ "{{ ansible_user_id }}" ] 

    - role: darkwizard242.lazygit
      become: true
      vars:
        lazygit_version: 0.51.1

    - role: Oefenweb.latest_r
      become: true
      vars:
        r_install_dev: true
        r_packages:
          - name: languageserver # Required for nvim config file
          - name: styler # Required for nvim autocompletion
          - name: tidyverse # Data wrangling meta package
          - name: tidymodels # Modeling meta package

    - role: Appsilon.quarto
      become: true

    - role: andrewrothstein.miniconda
      become: true
      vars:
        miniconda_make_sys_default: true  # This makes conda available in the system path

    - role: andrewrothstein.conda-env
      become: true # The role uses 'conda_env_escalate' which defaults to true
      vars:
        conda_env_name: datascience_stack # The name of the environment to create/manage
        conda_env_environment: files/datascience_stack.yml # Path to your environment definition file
        conda_env_update_if_present: true # Set to true to update if it already exists
        conda_env_activate_for_login_shell: true # Makes this environment active for new login shells

    - role: geerlingguy.nodejs
      become: true
      vars:
        nodejs_version: "20.x"
        nodejs_install_npm_user: "{{ ansible_user_id }}"

    - role: hurricanehrndz.rustup
      become: true # The role handles become internally for necessary tasks
      vars:
        rustup_user: "{{ ansible_user_id }}"
