# requirements.yml

roles:
  # Docker
  - src: geerlingguy.docker
    # You can specify a version if needed, e.g.:
    # version: 7.4.7

  # Neovim
  - src: gikeymarcia.neovim

  # Starship Prompt
  - src: andrewrothstein.starship

  # Nerdfont
  - src: hurricanehrndz.nerdfonts

  # Lazygit
  - src: darkwizard242.lazygit
