# requirements.yml

roles:
  # Docker
  - src: geerlingguy.docker
    # You can specify a version if needed, e.g.:
    # version: 7.4.7

  # Quarto
  - src: Appsilon.quarto
    # You can specify a version if needed, e.g.:
    # version: 1.0.2
