# roles/nerdfont/vars/main.yml

# Define the Nerd Font to install
nerdfont_name: "JetBrainsMono" # Example: "FiraCode", "JetBrainsMono", "Meslo", "RobotoMono", "SourceCodePro" 
nerdfont_version: "v3.4.0" # Check https://github.com/ryanoasis/nerd-fonts/releases for latest

# Construct the filename and download URL
nerdfont_filename: "{{ nerdfont_name }}.zip"
nerdfont_download_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/{{ nerdfont_version }}/{{ nerdfont_filename }}"

# Define user-specific font directories
user_font_dir: "{{ ansible_env.HOME }}/.local/share/fonts"
# Subdirectory within user_font_dir to keep this specific Nerd Font organized
nerdfont_install_subdir_name: "{{ nerdfont_name }}NerdFont"
nerdfont_install_path: "{{ user_font_dir }}/{{ nerdfont_install_subdir_name }}"

# Temporary download location
nerdfont_tmp_download_path: "/tmp/{{ nerdfont_filename }}"

