---
# file: roles/apt/vars/main.yml
# this will absolutely be used in this role
dev_tools:
  - build-essential
  - curl
  - fd-find
  - fonts-noto-color-emoji
  - fzf
  - git
  - imagemagick
  - libmagickwand-dev
  - lua5.1
  - liblua5.1-0-dev
  - luajit
  - make
  - ripgrep
  - tree-sitter-cli
  - tmux
  - unzip
  - wget
  - xclip
