# roles/apt/tasks/main.yml
- name: Provision local Tuxedo OS machine with development available via apt
  become: true  # Use sudo for tasks that require elevated privileges
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ dev_tools }}"
