# roles/R/defaults/main.yml

# The specific version of R to target for installation and symlinking.
r_target_version: "4.5.0"

# The base directory where different R versions are installed
# by the appsilon.r_language role.
r_install_base_path: "/opt/R"

# The target directory where symlinks for R executables will be created.
# This directory should be in the system PATH.
r_symlink_target_dir: "/usr/local/bin"

# List of R executables to symlink.
r_executables_to_symlink:
  - R
  - Rscript
