# roles/lazygit/defaults/main.yml

# Lazygit repository URL
lazygit_repo_url: "https://github.com/jesseduffield/lazygit.git"

# Version (git branch, tag, or commit) of Lazygit to build
lazygit_version: "master" # Or specify a release tag like "v0.40.2"

# Parent directory for cloning the Lazygit source code.
# The actual source will be in '{{ lazygit_build_parent_dir }}/lazygit'
lazygit_build_parent_dir: "{{ ansible_env.HOME }}/build"

# Set to true to force re-clone, rebuild and reinstall.
lazygit_force_rebuild: false

