# roles/ssh/tasks/main.yml

- name: Ensure ~/.ssh directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Copy SSH private key (ansible_tuxedo)
  ansible.builtin.copy:
    src: ansible_tuxedo # Refers to roles/ssh/files/ansible_tuxedo
    dest: "{{ ansible_env.HOME }}/.ssh/ansible_tuxedo"
    mode: '0600' # Critical: only owner can read/write
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Copy SSH public key (ansible_tuxedo.pub)
  ansible.builtin.copy:
    src: ansible_tuxedo.pub # Refers to roles/ssh/files/ansible_tuxedo.pub
    dest: "{{ ansible_env.HOME }}/.ssh/ansible_tuxedo.pub"
    mode: '0644' # Owner read/write, others read-only
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Ensure ~/.ssh/config exists and has correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    state: touch
    mode: '0600'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Add GitHub SSH config entry to ~/.ssh/config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.ssh/config"
    block: |
      Host github.com
          User git
          Hostname github.com
          PreferredAuthentications publickey
          IdentityFile ~/.ssh/ansible_tuxedo
    marker: "# {mark} ANSIBLE MANAGED BLOCK for github.com"
    create: yes
