# roles/starship/tasks/main.yml

- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Check if starship is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/starship" # Default install location for the script
  register: starship_binary_stat

- name: Download and install Starship using the official script
  ansible.builtin.shell:
    # Installs to ~/.local/bin by default, pass -b <dir> to change
    cmd: "curl -sS https://starship.rs/install.sh | sh -s -- --yes"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/starship"
  when: not starship_binary_stat.stat.exists
  changed_when: true # Assume change if the script runs
  environment: # Ensures script can find sh if not in default secure_path
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/bin"


- name: Ensure Starship is initialized in .bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      # Starship Prompt
      if command -v starship &> /dev/null; then
        eval "$(starship init bash)"
      fi
    marker: "# {mark} ANSIBLE MANAGED BLOCK for Starship Prompt"
    create: yes # Create .bashrc if it doesn't exist (though it should)
    mode: '0644'
